const shoppay = (prefix, pushname) => {
    return `💳| SHOPPAY |💳
 
https://kidscovetoys.com/ 
https://the120store.online?utm_source=shop_app 
https://www.120voltz.com/ 
https://1216dreams.com/ 
https://mensaccesories.com/ 
https://goldenlifewatches.com/ 
https://cfurniture.ca/ 
https://turbofly.co/ 
https://mercurysessentials.com/ 
https://rlb1225.com/ 
https://ays1246.com/ 
https://www.123nyfurniture.com/ 
https://electric-wave.com/ 
https://21golfco.com/ 
https://xycave.com/ 
https://evryjewels.com/ 
https://darnellmooney11.com/  
https://www.nohesiapparel.com 
https://www.slumerican.com/  
http://Fatsnax.com 
https://gainzbox.myshopify.com/ 
https://www.balr.com/ 
https://virallights.com/ 
https://www.must-have-gadgets.com 
https://theprolificshop.com/ 
http://revicedenim.com 
https://alphaomegacpu.com/ 
http://Cruzboxes.com 
https://au.tfiom.com/ 
https://doomsdayco.com/ 
http://majorwavezz.com 
https://tacticalsportsgear.com 
https://nitho.com/ 
https://unique-things-boutique.myshopify.com/ 
https://shop.lizardtechsolutions.com/collections/consoles/products/new-sony-playstation-5-ps5-disc-edition-gaming-console-glacier-white-825gb-ssd 
https://www.boomandtech.com/ 
https://www.whirlwindfx.com/ 
https://3700plusproducts.com/ 
https://416company.com/ 
https://1929galore.com/ 
https://shop.lycasmith.com/ 
https://droneskings.com/ 
https://7442drones.com/ 
https://shop746.com/ 
https://lolastoystore.com/ 
https://watchswagg.com/ 
https://v-g-73.myshopify.com/ 
https://www.xfyro.com/ 
https://shop.lycasmith.com/ 
https://atlasce.ca/ 
https://since83apparel.com/ 
https://www.gembrand.online/ 
https://westend86.com/ 
https://thewrightstuff87.com/ 
https://www.90srnbalumni.com/ 
https://101grabz.com/ 
https://www.101audiovideoinc.com/ 
https://www.101official.com/ 
https://boagadgets.com/ 
https://techsolutionsshop.com/ 
https://premiumboysclub.com/ 
https://premiumgames.shop/ 
https://elewatimepieces.com/ 
https://techknowlodge.com/ 
https://kenky20.com/ 
https://108limited.com/ 
https://empressbeardcare.com/ 
https://www.kstoys.store/ 
https://www.shopuseven.com/ 
https://retroarcadecrafts.com/ 
https://www.shopuseven.com/ 
https://itgirlzworldwide.com/ 
https://amp3dstore.com/ 
https://www.ettechnologies.space/ 
https://amiwel.com?utm_source=shop_app 
https://suretoshop.direct/ 
https://unashamed.shop/ 
https://smileskit.com/ 
https://streakbuy.com/ 
https://www.hotel1171.com/ 
https://117-llc.myshopify.com/ 
https://kuawabrand.com/ 
https://tiendajoyeriaadan.com/ 
https://1187luxurywatches.myshopify.com/ 
https://cleeduelec.com/ 
https://payelatraite.com/ 
https://www.bakerygang1117.com/`

}

exports.shoppay = shoppay
